services:
  app:
    build: .
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  queue:
    build: .
    container_name: laravel_queue
    command: php artisan queue:work
    volumes:
      - .:/var/www/html
    depends_on:
      - nginx

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Laravel_db
      MYSQL_USER: Laravel
      MYSQL_PASSWORD: "!QAZ8ill"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
  
  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  db_data: